### ISSUE TITLE
How to check from EIK if its have DDS registration?

### ISSUE THREAD

**Issue by sytolk** [mirovit/eik-validator#5]
In jobs.bg if I write EIK: 202228086 and check DDS NO here:
https://www.jobs.bg/company_registration.php

its appears error.. (its have DDS registration). Can I check the same with this php class?

**Comment by mirovit** [comment]
Hi there,

I couldn't find the feature that you've described for automatic check whether the company has VAT registration. Also I do not think that this should be a part of this package.

This package is only responsible for checking whether a number is valid according to the Bulstat registry algorithm. The described functionality would need to call an external API where it can check with a government service if the company has VAT registration. I was not able to find a service from the Bulgarian government, there is something from the EU, but haven't tried it.

Good luck with finding a solution to your problem.
